-- =============================================================================
-- HIPPOCRATES — ربط الموقع بنظام الحسابات في Google Sheets
-- شغّله مرة واحدة في Supabase SQL Editor. آمن لإعادة التشغيل أكثر من مرة.
--
-- هذا ملف تكامل فقط: ما يغيّر جدول الطلبات ولا الأسعار ولا منطق الشراء.
-- يضيف: حالة مزامنة مالية على الطلب · سجل محاولات · حالة آخر مزامنة كتالوك.
--
-- المنطق المالي (10/10/80 · Transactions · Subscriptions) يبقى كله في
-- Google Apps Script. ما ننسخه هنا.
-- =============================================================================


-- ── 0. فحص أمان قبل أي تعديل ─────────────────────────────────────────────────
-- جدول orders عنده تريكر يحمي أعمدة الفلوس من التعديل. أعمدة المزامنة الجديدة
-- ما موجودة بوقت كتابة ذاك التريكر، فغالباً ما راح يعترضها. بس إذا كان مكتوب
-- بأسلوب "قارن الصف كله" راح يمنع أي تحديث — فنوقف بصوت عالي بدل ما نكسر شي.

do $$
declare r record; src text;
begin
  for r in
    select tg.tgname as trigger_name, p.oid as fn_oid, p.proname as fn_name
      from pg_trigger   tg
      join pg_class     c on c.oid = tg.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      join pg_proc      p on p.oid = tg.tgfoid
     where n.nspname = 'public' and c.relname = 'orders' and not tg.tgisinternal
  loop
    src := pg_get_functiondef(r.fn_oid);

    if src ~* 'finance_sync_status' then
      raise notice 'التريكر % (%) يعرف أعمدة المزامنة أصلاً — تمام.', r.trigger_name, r.fn_name;

    elsif src ~* 'to_jsonb\s*\(\s*new' or src ~* 'row_to_json\s*\(\s*new' or src ~* 'new\s*is\s+distinct\s+from\s+old' then
      raise exception
        'توقّف: التريكر % (%) على public.orders يقارن الصف كامل، فراح يرفض تحديث أعمدة المزامنة الجديدة. عدّله ليسمح بالأعمدة: payment_method, payment_reference, confirmed_at, finance_sync_status, finance_synced_at, finance_sync_error, finance_sync_attempts — ثم أعد تشغيل هذا الملف.',
        r.trigger_name, r.fn_name;

    else
      raise notice 'التريكر % (%) يثبّت أعمدة محددة بالاسم — أعمدة المزامنة الجديدة ما تتأثر.', r.trigger_name, r.fn_name;
    end if;
  end loop;
end $$;


-- ── 1. أعمدة الدفع والمزامنة على الطلب ───────────────────────────────────────
-- ما نضيف نظام طلبات ثاني. نضيف أقل عدد ممكن من الأعمدة على نفس الجدول.

alter table public.orders
  add column if not exists payment_method    text,
  add column if not exists payment_reference text,
  add column if not exists confirmed_at      timestamptz,

  add column if not exists finance_sync_status   text not null default 'not_synced',
  add column if not exists finance_synced_at     timestamptz,
  add column if not exists finance_sync_error    text,
  add column if not exists finance_sync_attempts integer not null default 0;

-- طريقة الدفع الحالية للموقع. القيمة لازم تطابق القيمة الموجودة بنظام الحسابات.
alter table public.orders
  alter column payment_method set default 'SuperQi';

update public.orders set payment_method = 'SuperQi' where payment_method is null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'orders_finance_sync_status_check'
       and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_finance_sync_status_check
      check (finance_sync_status in ('not_synced', 'syncing', 'synced', 'sync_error'));
  end if;
end $$;

create index if not exists orders_finance_sync_status_idx
  on public.orders (finance_sync_status)
  where finance_sync_status <> 'synced';

-- الطلبات المؤكدة قبل التكامل: نخليها not_synced حتى تقدر تزامنها يدوياً
-- من زر "إعادة المزامنة". ما نلمس حالة الدفع ولا المبالغ.
update public.orders
   set confirmed_at = coalesce(confirmed_at, created_at)
 where status = 'confirmed' and confirmed_at is null;


-- ── 2. سجل محاولات المزامنة ──────────────────────────────────────────────────
-- كل نداء للويبهوك ينحفظ هنا: الطلب المرسل، الرد، الخطأ. هذا اللي يخلينا
-- نعرف بالضبط شنو صار إذا فشلت مزامنة، بدل التخمين.

create table if not exists public.finance_sync_log (
  id          bigint generated by default as identity primary key,
  order_id    uuid references public.orders (id) on delete cascade,
  action      text not null,                 -- confirm_sale | sync_catalog
  ok          boolean not null default false,
  http_status integer,
  request     jsonb,                          -- بدون السر أبداً
  response    jsonb,
  error       text,
  created_at  timestamptz not null default now()
);

create index if not exists finance_sync_log_order_idx
  on public.finance_sync_log (order_id, created_at desc);
create index if not exists finance_sync_log_created_idx
  on public.finance_sync_log (created_at desc);


-- ── 3. حالة آخر مزامنة كتالوك (صف واحد فقط) ─────────────────────────────────
create table if not exists public.finance_catalog_sync (
  id              boolean primary key default true check (id),
  status          text not null default 'not_synced'
                  check (status in ('not_synced', 'syncing', 'synced', 'partial', 'failed')),
  synced_at       timestamptz,
  courses_sent    integer not null default 0,
  packages_sent   integer not null default 0,
  courses_mapped  integer,
  packages_mapped integer,
  issues          jsonb not null default '[]'::jsonb,   -- المنتجات اللي فشل ربطها
  error           text,
  by_email        text
);

insert into public.finance_catalog_sync (id) values (true)
on conflict (id) do nothing;


-- ── 4. الصلاحيات: القراءة للمدراء فقط، والكتابة للسيرفر فقط ──────────────────
-- الكتابة كلها تجي من Edge Function بمفتاح الخدمة (يتجاوز RLS)، فما نحتاج
-- سياسة كتابة لأي مستخدم. المتصفح يقرأ فقط.

alter table public.finance_sync_log     enable row level security;
alter table public.finance_catalog_sync enable row level security;

drop policy if exists finance_sync_log_read     on public.finance_sync_log;
drop policy if exists finance_catalog_sync_read on public.finance_catalog_sync;

create policy finance_sync_log_read
  on public.finance_sync_log for select
  using (public.is_admin());

create policy finance_catalog_sync_read
  on public.finance_catalog_sync for select
  using (public.is_admin());

grant select on public.finance_sync_log     to authenticated;
grant select on public.finance_catalog_sync to authenticated;


-- ── 5. تحقّق ─────────────────────────────────────────────────────────────────
select
  (select count(*) from public.orders where finance_sync_status = 'not_synced') as orders_not_synced,
  (select count(*) from public.orders where status = 'confirmed')               as confirmed_orders,
  (select status from public.finance_catalog_sync where id)                     as catalog_sync_status;
